### PR TITLE
make df.style render directly to HTML

### PR DESCRIPTION
**Pull request by jreback**
add align style
example updated in style.ipynb

### CODE REVIEW

**Comment by jreback** [comment]
@TomAugspurger 

- added an align style
- make ``df.style`` render directly to html
- updated an example in the style notebook

**Comment by TomAugspurger** [comment]
Thanks. I might change the `side` to `direction` to match the CSS term: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

**Comment by jreback** [comment]
cool

side issue is I suspect formatting shouldn't touch the index/columns at all unless specifically directed

**Comment by jreback** [comment]
@TomAugspurger 

I think this would be a nice little show-and-tell to add onto part of a talk I am giving at upcoming PyDataNYC 2015. (nov 9), on whats-new-in-pandas (this is in the 'future features')

also stealing parts of your PyDataSeattle tutorial :)

**Comment by TomAugspurger** [comment]
Steal away :)

It's nice to have a "deadline" for some extra motivation. I'll try to get a working version done this week.

**Comment by jreback** [comment]
hahha sure. 

And I think we could certainly include an experimental / demo version (maybe in 0.17.1), prob due mid-nov sometime.

And I think what you have is pretty extensible.

**Pull request merged**
