### PR TITLE
Rebased #24024

### PR DESCRIPTION
**Pull request by jbrockmendel**
Haven't run tests locally, so definitely wait for CircleCI to give an OK

### CODE REVIEW

**Comment by jbrockmendel** [comment]
dont see any Circle results, but tests passed locally overnight.

**Comment by TomAugspurger** [comment]
It seems like there are unrelated commits like 
https://github.com/TomAugspurger/pandas/pull/7/commits/95f73c3dab1eb472d27121c09723b8abeab9eeb7 in here. Is that what we want? Shouldn't this just be a "Merged branch master into ..." commit?

**Comment by jbrockmendel** [comment]
> It seems like there are unrelated commits like

It's totally plausible that I screwed up the git-fu.  I just ran "git pull upstream master" (actually" git pull u2 master" since "u2" points towards pandas-dev/pandas) and then cleaned up merge conflicts.

Prefer "git rebase upstream/master"?

**Comment by TomAugspurger** [comment]
Hmm that sounds right. It's just hard to see what actually changed on this
diff.

**Comment by jbrockmendel** [comment]
> It's just hard to see what actually changed on this diff.

Yah, I'm going through it now to see if the result of "git rebase" is any better.  The asv and _libs diffs all look unrelated, we'll see if any other big chunks can be declared ignoreable.

**Comment by jbrockmendel** [comment]
So this might just be recursing on the original problem, but I _could_ break this rebase-PR into smaller PRs rebasing less-recent masters

**Comment by TomAugspurger** [comment]
I guess I'm just not sure what the expected behavior of GitHub's UI is here. Presumably once this is merged it'll be easier to see what's changed relative to pandas-dev/pandas:master.

**Pull request merged**
